import { useMetaData } from '@/hooks'
import { http } from '@/utils'
import { Metadata } from 'next'

const meta = await http('/meta/uuid')

export const metadata: Metadata = useMetaData({
	title: meta[0],
	// description: 'Generated by create next app',
	keywords: meta[1],
})

const Uuid: React.FC = () => {
	return <>uuid</>
}

export default Uuid
