import type { Metadata } from 'next'
import './globals.css'

import StyledComponentsRegistry from '../lib/AntdRegistry'
import { ConfigProvider } from 'antd'
import { lightTheme } from '@/theme'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="zh-CN">
			<body>
				<StyledComponentsRegistry>
					<ConfigProvider theme={lightTheme}>{children}</ConfigProvider>
				</StyledComponentsRegistry>
			</body>
		</html>
	)
}
